/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package internalPages;

import config.config;
import javax.swing.JOptionPane;

/**
 *
 * @author SarWins NetSpot
 */
public class transactionPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form transactionPage
     */
    public transactionPage() {
        initComponents();
        displayData();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void displayData() {
    config cn = new config();
    try {
        // Fetch products that are 'Available'
        String query = "SELECT p_id, p_name, p_price, p_stock FROM tbl_products WHERE p_status = 'Available'";
        cn.fillTable(query, jTable1); // Fills your table
    } catch (Exception e) {
        System.out.println("Error Loading Table: " + e.getMessage());
    }
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tx_qty = new javax.swing.JTextField();
        tx_customer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CONFIRM = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(686, 396));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 99, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Price", "Available Stock"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 430, 320));

        lbl_total.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 110, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUANTITY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 110, -1));

        tx_qty.addActionListener(this::tx_qtyActionPerformed);
        tx_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_qtyKeyReleased(evt);
            }
        });
        jPanel1.add(tx_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 110, -1));

        tx_customer.addActionListener(this::tx_customerActionPerformed);
        jPanel1.add(tx_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CUSTOMER NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 110, -1));

        CONFIRM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CONFIRM.setText("CONFIRM");
        CONFIRM.addActionListener(this::CONFIRMActionPerformed);
        jPanel1.add(CONFIRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("SEARCH");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_qtyActionPerformed

    private void tx_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_customerActionPerformed

    private void CONFIRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRMActionPerformed
        config cn = new config();
    int rowIndex = jTable1.getSelectedRow();

    // 1. Validation: Ensure a product is selected from the table
    if (rowIndex == -1) {
        JOptionPane.showMessageDialog(null, "Please select a product first.");
        return;
    }

    try {
        // 2. Define the missing symbols by pulling from UI
        String pid = jTable1.getValueAt(rowIndex, 0).toString(); 
        int currentStock = Integer.parseInt(jTable1.getValueAt(rowIndex, 3).toString());
        int qtySold = Integer.parseInt(tx_qty.getText());

        // 3. Stock Check
        if (qtySold > currentStock) {
            JOptionPane.showMessageDialog(null, "Insufficient Stock!");
        } else {
            String totalStr = lbl_total.getText().replace("TOTAL: ₱", "");
            double totalVal = Double.parseDouble(totalStr);

            // 4. Record Master Order
            cn.insertData("INSERT INTO tbl_order (o_date, o_total) VALUES (datetime('now'), " + totalVal + ")");

            // 5. Get the new Order ID using the helper method
            int orderId = cn.getLatestID("SELECT o_id FROM tbl_order ORDER BY o_id DESC LIMIT 1");

            // 6. Record Specific Order Item
            cn.insertData("INSERT INTO tbl_order_item (o_id, p_id, oi_qty, oi_subtotal) "
                        + "VALUES (" + orderId + ", " + pid + ", " + qtySold + ", " + totalVal + ")");

            // 7. Deduct from Inventory
            cn.updateData("UPDATE tbl_products SET p_stock = p_stock - " + qtySold + " WHERE p_id = '" + pid + "'");

            JOptionPane.showMessageDialog(null, "Transaction Recorded Successfully!");
            
            // 8. Refresh and Clear
            displayData();
            tx_customer.setText("");
            tx_qty.setText("");
            lbl_total.setText("TOTAL: ₱0.00");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_CONFIRMActionPerformed

    private void tx_qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_qtyKeyReleased
        try {
        int rowIndex = jTable1.getSelectedRow();
        if(rowIndex != -1){
            // Price is at index 2
            double price = Double.parseDouble(jTable1.getValueAt(rowIndex, 2).toString()); 
            int qty = Integer.parseInt(tx_qty.getText());
            double total = price * qty;
            lbl_total.setText("TOTAL: ₱" + total);
        }
    } catch (NumberFormatException e) {
        lbl_total.setText("TOTAL: ₱0.00");
    }
    }//GEN-LAST:event_tx_qtyKeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        config cn = new config();
    String search = jTextField1.getText();
    // Search by Name or ID where product is available
    String query = "SELECT p_id, p_name, p_price, p_stock FROM tbl_products "
                 + "WHERE (p_name LIKE '%" + search + "%' OR p_id LIKE '%" + search + "%') "
                 + "AND p_status = 'Available'";
    cn.fillTable(query, jTable1);
    }//GEN-LAST:event_jTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONFIRM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField tx_customer;
    private javax.swing.JTextField tx_qty;
    // End of variables declaration//GEN-END:variables
}
