/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import config.Session;
import config.config;
import javax.swing.JOptionPane;

/**
 *
 * @author USER15
 */
public class userAccount extends javax.swing.JInternalFrame {

    /**
     * Creates new form userAccount
     */
    public userAccount() {
        initComponents();
        Session sess = Session.getInstance();
    
    // Display the data in your renamed labels
    id_display.setText("" + sess.getId());
    email_display.setText(sess.getName());
    email_display.setText(sess.getEmail());
    type_display.setText(sess.getType());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        type_display = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id_display = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        email_display = new javax.swing.JTextField();
        name_display = new javax.swing.JTextField();

        setRequestFocusEnabled(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACCOUNT SETTINGS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 30));

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("TYPE:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, 30));

        type_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(type_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("ACCOUNT ID:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 30));

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("NAME:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 30));

        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("EMAIL:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 30));

        id_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(id_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, 30));

        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        email_display.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_displayActionPerformed(evt);
            }
        });
        jPanel2.add(email_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, 30));

        name_display.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_displayActionPerformed(evt);
            }
        });
        jPanel2.add(name_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 110, 30));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 680, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        Session ses = Session.getInstance();
    
    id_display.setText("" + ses.getId());
    name_display.setText(ses.getName());
    email_display.setText(ses.getEmail());
    type_display.setText(ses.getType());
    }//GEN-LAST:event_formInternalFrameActivated

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        config cn = new config();
    Session sess = Session.getInstance();
    
    String newName = name_display.getText();
    String newEmail = email_display.getText();

    // Corrected column names based on your tbl_accounts structure
    String sql = "UPDATE tbl_accounts SET name = '" + newName + "', "
               + "email = '" + newEmail + "' "
               + "WHERE a_id = " + sess.getId(); // Use 'a_id' and 'name'

    cn.updateData(sql);
    
    // Sync the session so the change is global
    sess.setName(newName);
    sess.setEmail(newEmail);
    
    JOptionPane.showMessageDialog(null, "Profile updated successfully!");


    }//GEN-LAST:event_btn_updateActionPerformed

    private void email_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_displayActionPerformed

    private void name_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_displayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JTextField email_display;
    private javax.swing.JLabel id_display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name_display;
    private javax.swing.JLabel type_display;
    // End of variables declaration//GEN-END:variables
}
