/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import config.config;
import javax.swing.JOptionPane;

/**
 *
 * @author SarWins NetSpot
 */
public class userAccountForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(userAccountForm.class.getName());

    /**
     * Creates new form userAccountForm
     */
    public userAccountForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tx_id = new javax.swing.JTextField();
        tx_name = new javax.swing.JTextField();
        tx_email = new javax.swing.JTextField();
        tx_type = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tx_id.addActionListener(this::tx_idActionPerformed);
        jPanel2.add(tx_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 72, 113, -1));

        tx_name.addActionListener(this::tx_nameActionPerformed);
        jPanel2.add(tx_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 106, 113, -1));

        tx_email.addActionListener(this::tx_emailActionPerformed);
        jPanel2.add(tx_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 140, 113, -1));

        tx_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(tx_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_save.setText("SAVE");
        btn_save.addActionListener(this::btn_saveActionPerformed);
        jPanel2.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 610, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Background.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_idActionPerformed

    private void tx_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_nameActionPerformed

    private void tx_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_emailActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if(btn_save.getText().equals("ADD")) {
    config cn = new config();
    // Ensure column names match: name, email, type, status
    cn.insertData("INSERT INTO tbl_accounts (name, email, type, status) "
            + "VALUES ('" + tx_name.getText() + "', '" + tx_email.getText() + "', "
            + "'" + tx_type.getSelectedItem() + "', 'Pending')");
    
    JOptionPane.showMessageDialog(null, "Registration Successful!");
    
    adminDashboard ds = new adminDashboard();
    ds.setVisible(true);
    this.dispose();

}
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new userAccountForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField tx_email;
    public javax.swing.JTextField tx_id;
    public javax.swing.JTextField tx_name;
    private javax.swing.JComboBox<String> tx_type;
    // End of variables declaration//GEN-END:variables
}
